services:
  postgres:
    image: postgres:15-alpine
    container_name: nir_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: NIRdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Config/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: